version: "3.9"
services:
  app:
    container_name: homeassistant_bluetooth_mesh
    build: .
    volumes:
      - ./config:/config/
    restart: "always"
    network_mode: "host"
    privileged: true
    tty: true
